#!/usr/bin/env node
const getopts = require("../")

console.log(
  getopts(process.argv.slice(2), {
    alias: {
      j: "jet",
      m: "mode",
      u: "ultra"
    },
    boolean: ["jet"],
    default: {
      bolt: true,
      hyper: true
    }
  })
)
