#!/usr/bin/env node
const getopts = require("../")

console.log(
  getopts(process.argv.slice(2), {
    alias: {
      j: "jet",
      m: "mode",
      v: "viper"
    },
    default: {
      bolt: true,
      hyper: 9000
    }
  })
)
