#!/usr/bin/env node

const getopts = require("..")

const options = getopts(process.argv.slice(2), {
  alias: {
    help: "h",
    length: "l",
    digits: "d",
    symbols: "s"
  },
  default: {
    length: 16,
    digits: true,
    symbols: true
  }
})

if (options.help) {
  console.log("usage: pwd [-l|--length=N] [--no-digits] [--no-symbols]")
  process.exit(0)
}

const CHARS =
  "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ" +
  (options.digits ? "0123456789" : "") +
  (options.symbols ? "!@#$%^&*()_+~`|}{[]:;?><,./-=" : "")

const getRandom = list => list.charAt(Math.floor(Math.random() * list.length))

process.stdout.write(
  Array.from({ length: options.length }, () => getRandom(CHARS)).join("") + "\n"
)
